format = """\
[<](244)\
$directory\
$git_branch\
[>](244)\
$character\
"""
# [󰀵 ](244)\
# [-](244)\
# $time\
# [](244)\
# $directory\
# [](244)\

# [-](fg:#3B76F0 bg:#FCF392)\

[directory]
format = "[$path/]($style)[$read_only]($read_only_style)"
style = "white"
read_only = " "
read_only_style = "52"
disabled = false
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[ $symbol$branch(:$remote_branch)]($style)'
symbol = " "
style = "108"

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[character]
success_symbol = '[:](108) '
error_symbol = '[:](52) '

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# format = '[[ 󱑍 $time ](fg:108)]($style)'
