github.com:
    users:
        warrenjkim:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: warrenjkim
